import { NextRequest } from 'next/server'
import { GoogleGenerativeAI } from '@google/generative-ai'

// ── System prompts ──────────────────────────────────────────────────────────

function buildSystemPrompt(lang: string): string {
  if (lang === 'en') {
    return `You are MYTCM AI, a professional Traditional Chinese Medicine (TCM) health advisor on the MYTCM Malaysia platform. Your guidelines:
- Respond entirely in English with a warm, professional, and empathetic tone
- Structure answers clearly: use **bold** for key TCM terms and important points; break content into short, readable paragraphs
- Analyse the user's symptoms from a TCM perspective (e.g. Qi deficiency, dampness, Liver Qi stagnation, Yin/Yang imbalance)
- Give practical, specific daily diet and food therapy recommendations
- Suggest 1–2 acupressure points where relevant (include point name and location)
- Keep the total response under 350 words
- If symptoms sound serious or acute, prioritise advising the user to seek a doctor immediately
- ALWAYS end every response with this exact line:
  "⚠️ AI consultation is for general wellness reference only and does not constitute medical diagnosis. For personalised care, browse authentic Tongrentang formulas in our shop, or book a licensed TCM doctor on the MYTCM platform."`
  }

  return `你是 MYTCM（大马中医）平台的专业 AI 中医健康顾问。你的行为准则：
- 全程用中文回复，语气礼貌、专业、亲切
- 回答结构清晰：用 **粗体** 标注中医关键术语及重点；合理分段，便于阅读
- 从中医角度分析用户描述的症状（如气虚、湿热、肝郁气滞、阴阳失调等）
- 给出具体可行的日常饮食、食疗调理建议
- 适当推荐 1–2 个可自行按压的穴位（注明穴位名称及位置）
- 回答控制在 350 字以内，简洁有力
- 若症状听起来严重或急性，优先建议立即就医，而非只给调理建议
- 每次回答结尾必须加上以下这行提示：
  "⚠️ AI 问诊仅供参考，不构成医疗诊断。如需调理用药，欢迎前往商城选购同仁堂正品中成药；如需专业诊治，可预约 MYTCM 平台持牌中医师。"`
}

// ── Prompt builder: injects history as plain text, zero role-format errors ──

function buildPrompt(
  messages: Array<{ role: string; content: string }>,
  lang: string
): string {
  const system = buildSystemPrompt(lang)

  // Skip index 0 (the frontend UI welcome message — never generated by the model)
  // Keep last 8 messages for context without hitting token limits
  const context = messages.slice(1).slice(-8)

  if (context.length === 0) {
    return system
  }

  const userLabel = lang === 'en' ? 'User' : '用户'
  const aiLabel = 'MYTCM AI'

  const history = context
    .map((m) => `${m.role === 'user' ? userLabel : aiLabel}: ${m.content}`)
    .join('\n\n')

  return `${system}\n\n--- Conversation ---\n\n${history}\n\n${aiLabel}:`
}

// ── Fallback responses when API key is absent ────────────────────────────────

const FALLBACK_ZH = `**感谢您的提问！**

AI 问诊服务正在为您开通，请稍后再试。

**您现在也可以：**
- 预约 MYTCM 平台持牌中医师进行面诊
- 前往商城选购同仁堂经典中成药

⚠️ AI 问诊仅供参考，不构成医疗诊断。`

const FALLBACK_EN = `**Thank you for your question!**

The AI consultation service is being activated. Please try again shortly.

**In the meantime:**
- Book a licensed MYTCM TCM doctor for a consultation
- Browse our shop for authentic Tongrentang products

⚠️ AI guidance is for wellness reference only, not medical diagnosis.`

// ── Route handler ────────────────────────────────────────────────────────────

export async function POST(request: NextRequest) {
  console.log('[chat] ✅ Using NEW chat API — v3 streaming rewrite')

  let body: { messages?: Array<{ role: string; content: string }>; lang?: string }
  try {
    body = await request.json()
  } catch {
    return new Response('Invalid request body', { status: 400 })
  }

  const { messages = [], lang = 'zh' } = body
  const apiKey = process.env.GEMINI_API_KEY
  console.log('[chat] API key present:', !!apiKey, '| lang:', lang, '| messages:', messages.length)

  // No API key → return rich static fallback (still readable by the streaming reader)
  if (!apiKey) {
    return new Response(lang === 'en' ? FALLBACK_EN : FALLBACK_ZH, {
      headers: { 'Content-Type': 'text/plain; charset=utf-8' },
    })
  }

  const prompt = buildPrompt(messages, lang)

  try {
    const genAI = new GoogleGenerativeAI(apiKey)
    const model = genAI.getGenerativeModel({
      model: 'gemini-1.5-flash-latest',
      generationConfig: {
        maxOutputTokens: 600,
        temperature: 0.75,
      },
    })

    // Single generateContentStream call — no startChat, no history array, no role errors
    const streamResult = await model.generateContentStream(prompt)

    const encoder = new TextEncoder()
    const readable = new ReadableStream({
      async start(controller) {
        try {
          for await (const chunk of streamResult.stream) {
            const text = chunk.text()
            if (text) controller.enqueue(encoder.encode(text))
          }
        } catch (streamErr) {
          console.error('[chat:stream]', streamErr)
          const msg =
            lang === 'zh'
              ? '\n\n⚠️ 回答生成中断，请重试。'
              : '\n\n⚠️ Response interrupted. Please try again.'
          controller.enqueue(encoder.encode(msg))
        } finally {
          controller.close()
        }
      },
    })

    return new Response(readable, {
      headers: {
        'Content-Type': 'text/plain; charset=utf-8',
        'Cache-Control': 'no-cache, no-store',
        'X-Accel-Buffering': 'no', // disable Nginx/proxy buffering for streaming
      },
    })
  } catch (err) {
    console.error('[chat]', err)
    const msg =
      lang === 'zh'
        ? '**抱歉**，AI 服务暂时不可用，请稍后再试。\n\n⚠️ AI 问诊仅供参考，不构成医疗诊断。'
        : '**Sorry**, the AI service is temporarily unavailable. Please try again later.\n\n⚠️ For reference only, not medical advice.'
    return new Response(msg, {
      headers: { 'Content-Type': 'text/plain; charset=utf-8' },
    })
  }
}
